#!../env/bin/python

from time import sleep, time
import threading
import json

import aiohttp
import asyncio

import gzip

KEEPALIVE_WINDOW_S = 10

class TradeStreamer:
    def __init__(ᬑ, symbols, on_trade, verbose=False, discard_priors=False):
        ᬑ.symbols = symbols
        ᬑ.on_trade = on_trade
        ᬑ.verbose = verbose
        ᬑ.discard_priors = discard_priors

        ᬑ.nothing_yet = { s: True  for s in symbols }
        ᬑ.trades = { s: []  for s in symbols }

        ᬑ.terminate_flag = False

        ᬑ.worker_thread = threading.Thread(
            name='tradestreamer',
            target=ᬑ.worker_thread_func,
            daemon=True
            )

    def start_streaming(ᬑ):
        ᬑ.worker_thread.start()


    def terminate(ᬑ):
        ᬑ.terminate_flag = True


    def worker_thread_func(ᬑ):
        asyncio.run(ᬑ.aio_func())  # blocks


    async def aio_func(ᬑ):

        def vprint(*args):
            if ᬑ.verbose:
                print(*args)

        # https://github.com/hotbitex/hotbit.io-api-docs/blob/master/websocket_api_en.md

        URL = 'wss://ws.hotbit.io'

        async with aiohttp.ClientSession() as session:

            async with session.ws_connect(URL) as wsock:

                # https://github.com/hotbitex/hotbit.io-api-docs/blob/master/websocket_api_en.md#subscription-of-settled-deals

                def extract_data(msg):
                    if msg.type == aiohttp.WSMsgType.BINARY:
                        as_bytes = gzip.decompress(msg.data)

                        as_string = as_bytes.decode('utf8')

                        as_json = json.loads(as_string)

                        return as_json

                    else:
                        print('FAILED to decompress')
                        return msg.data

                ID_PING = 101
                ID_TRADES = 666

                J = {
                    'method': 'deals.subscribe', 
                    'params': ᬑ.symbols, 
                    'id': ID_TRADES
                }
                vprint('sending: ')
                vprint(J)
                vprint()

                await wsock.send_json(J)

                data = extract_data( await wsock.receive() )

                # e.g.: {'error': None, 'result': {'status': 'success'}, 'id': 100}
                vprint(data)

                t = time()
                async for msg in wsock:
                    # trade-stream msg looks like e.g.:
                    #     {
                    #         'method': 'deals.update',
                    #         'params': [
                    #             'ETHUSDT', [
                    #                 {'id': 2293687412, 'time': 1622752432.785998, 'price': '2802.76', 'amount': '0.48331', 'type': 'buy'},
                    #                 {...},
                    #                 ...
                    #             ]
                    #         ],
                    #         'id': None,
                    #         'ts': 1622752877
                    #     }
                    data = extract_data(msg)
                    vprint(data)

                    # if data['id'] == ID_TRADES:  # cannot use this as 'id' is None (I think this is a HotBit bug)
                    if 'method' in data.keys() and data['method'] == 'deals.update':
                        symbol, trades = data['params']

                        # trades come in most recent first, so reverse list as we want OLDEST first
                        oldest_first = trades[::-1]

                        ignore = ᬑ.discard_priors and ᬑ.nothing_yet[symbol]
                        if not ignore:
                            for trade in oldest_first:
                                ᬑ.on_trade(symbol, trade)

                            ᬑ.trades[symbol] += oldest_first

                        ᬑ.nothing_yet[symbol] = False

                    # ping to keep connection alive
                    if time() > t+KEEPALIVE_WINDOW_S:
                        t += KEEPALIVE_WINDOW_S
                        await wsock.send_json({
                            'method': 'server.ping',
                            'params': [],
                            'id': ID_PING
                        })

                    if ᬑ.terminate_flag:
                        print('Closing Stream Socket')
                        await wsock.close()
                        break

        print('👋 from TradeStreamer')


    def dump_trades(ᬑ):
        for symbol, trades in ᬑ.trades.items():
            print(symbol)
            print(trades)
            print()

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

if __name__ == '__main__':

    symbols = ['ETHUSDT', 'BTCUSDT']

    # {'id': 2293687412, 'time': 1622752432.785998, 'price': '2802.76', 'amount': '0.48331', 'type': 'buy'},
    def on_trade(symbol, trade):
        print('GOT TRADE:', symbol)

    rt_streamer = TradeStreamer(symbols, on_trade, verbose=True, discard_priors=True)

    rt_streamer.start_streaming()

    try:
        while True:
            sleep(1)

    except KeyboardInterrupt:
        rt_streamer.terminate()

        print()
        rt_streamer.dump_trades()

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


# all_symbols = ['ZLWUSDT', 'CTSIUSDT', 'RFOXUSDT', 'SHDCUSDT', 'QUINUSDT', 'FRONTUSDT', 'RARIUSDT', 'TARAXAUSDT', 'LHBUSDT', 'XCHUSDT', 'LEMDUSDT', 'GRFTUSDT', 'OXYUSDT', 'BPSUSDT', 'SUNUSDT', 'BSOCIALUSDT', 'BFLYUSDT', 'YSOYUSDT', 'DYNMTUSDT', 'Q8E20USDT', 'TTUSDT', 'GMMUSDT', 'QOBUSDT', 'MNSTPUSDT', 'GLOXUSDT', 'COMP1D3LUSDT', 'XMR1D3LUSDT', 'NOVAUSDT', 'XMRUSDT', 'LOTTOUSDT', 'DIAUSDT', 'SAFEZONEUSDT', 'SNNBSCUSDT', 'QNTUSDT', 'WSFUSDT', 'CHIUSDT', 'RLYUSDT', 'UPUSDT', 'SWINGBYUSDT', 'ZYROUSDT', 'ZUPIUSDT', 'WALLUSDT', 'MTAUSDT', 'ZENUSDT', 'BADGERUSDT', 'XVSUSDT', 'SDFIUSDT', 'KP4RUSDT', 'VTHOUSDT', 'TRX1D3SUSDT', 'OMUSDT', 'SASHIMIUSDT', 'SPRAYUSDT', 'RAIFIUSDT', 'DDKUSDT', 'ANTUSDT', 'FXSUSDT', 'DEUSUSDT', 'MATHUSDT', 'XTZUSDT', 'BMIUSDT', 'FSXUUSDT', 'DNAUSDT', 'EFINUSDT', 'SNBLUSDT', 'PROMUSDT', 'BOSONUSDT', 'BANKUSDT', 'RENUSDT', 'FACTUSDT', 'CFBUSDT', 'AAVE1D3SUSDT', 'XDBUSDT', 'BUNNYUSDT', 'AUCTIONUSDT', 'APMUSDT', 'CELRUSDT', 'PGOUSDT', 'ENTRCUSDT', '1INCH12MUSDT', 'A5TUSDT', 'DPRUSDT', 'PPCUSDT', 'UNICORNUSDT', 'CREDITUSDT', 'DUSDUSDT', 'DPIUSDT', 'XCH1D3LUSDT', 'SASUSDT', 'FORTHUSDT', 'MITxUSDT', 'AAVE1D3LUSDT', 'LCXUSDT', 'COFEUSDT', 'RABBITUSDT', 'MASHUSDT', 'DOGIRAUSDT', 'BSCUSDT', 'KINGUSDT', 'AGSUSDT', 'LINAUSDT', 'SHIB1D3SUSDT', 'BSHA3USDT', 'DMDUSDT', 'TOMUSDT', 'LMCUSDT', 'USDKUSDT', 'TSHPUSDT', 'NEARUSDT', 'DDIMUSDT', 'DCASHUSDT', 'STARUSDT', 'CMCTUSDT', 'DGUSDT', 'FETUSDT', 'DOGE1D3LUSDT', 'SPAUSDT', 'VIDYUSDT', 'MXCUSDT', 'BTT1D3SUSDT', 'KCASHUSDT', 'MADUSDT', 'INDEXEDUSDT', 'YFIGUSDT', 'GSDUSDT', 'ALEPHUSDT', 'DEXEUSDT', 'ZRXUSDT', 'DDXUSDT', 'DOT1D3SUSDT', 'HARDUSDT', 'KEXUSDT', 'MFTUSDT', 'MARSPLUSDT', 'DAPSUSDT', 'BSVUSDT', 'TWIUSDT', 'MATICUSDT', 'PISUSDT', 'EGTUSDT', 'BBLUSDT', 'VSYSUSDT', 'TIGERUSDT', 'OGCUSDT', 'SDOGEUSDT', 'KXCUSDT', 'TRADEUSDT', 'BCHAUSDT', 'RSRUSDT', 'LUNA1D3SUSDT', 'HSNUSDT', 'TRIBEUSDT', 'CNTRUSDT', 'INJUSDT', 'OKBUSDT', 'VITEUSDT', 'HGETUSDT', 'ACSUSDT', 'SMUDGEUSDT', 'CROUSDT', 'NDXUSDT', 'POODLUSDT', 'SUSHI1D3LUSDT', 'ABTUSDT', 'YEYUSDT', 'LAYERUSDT', 'BTC1D3SUSDT', 'LUNAUSDT', 'YFIBUSDT', 'BDTUSDT', 'OPIUMUSDT', 'PAIDUSDT', 'HTNUSDT', 'VANCIIUSDT', 'LATUSDT', 'RAKBUSDT', 'HEXUSDT', 'QCXUSDT', 'MBLUSDT', 'SRKUSDT', 'FASTUSDT', 'CTRTUSDT', 'AKROUSDT', 'EXEUSDT', 'YFDOTUSDT', 'IDVUSDT', 'DCNUSDT', 'FILUSDT', 'GHSTUSDT', 'UGASUSDT', 'DAIUSDT', 'MCBUSDT', 'YFIXUSDT', 'SAPUSDT', 'PETUSDT', 'EARNXUSDT', 'WAVES1D3SUSDT', 'ANKUSDT', 'AXSUSDT', 'UNIFIUSDT', 'EVNYUSDT', 'KNCUSDT', 'XXPUSDT', 'HDSUSDT', 'GRINUSDT', 'JEMUSDT', 'CPIUSDT', 'LSTUSDT', 'BUSDUSDT', 'SUPERUSDT', 'ELTUSDT', 'SWFTCUSDT', 'HATCHUSDT', 'BFIUSDT', 'CLUUSDT', 'USTUSDT', 'TRBUSDT', 'ITENUSDT', 'CANUSDT', 'BNSDUSDT', 'STPCUSDT', 'NFTXUSDT', 'ETTUSDT', 'BANDOTUSDT', 'XTZ1D3LUSDT', 'ROYAUSDT', 'SUTERUSDT', 'SVXUSDT', 'DDRTUSDT', 'TBEUSDT', '1INCH1D3LUSDT', 'INDEXUSDT', 'AVAXUSDT', 'FILECASHUSDT', 'ZEEUSDT', 'DEEPUSDT', 'RZNUSDT', 'CTKUSDT', 'RVXUSDT', 'STABLEUSDT', 'HMTUSDT', 'REVVUSDT', 'MKUSDT', 'XMR1D3SUSDT', 'VSPUSDT', 'TADUSDT', 'TCRUSDT', 'VIDYAUSDT', 'FLUX01USDT', 'CORAUSDT', 'COCOSUSDT', 'BNT1D3LUSDT', 'ELCASHUSDT', 'LRCUSDT', 'PLOWUSDT', 'BSDSUSDT', 'WHITEUSDT', 'ICP1D3LUSDT', 'ILVUSDT', 'BUSYUSDT', 'XCH1D3SUSDT', 'IDXUSDT', 'HNBUSDT', 'GODUSDT', 'XUCUSDT', 'KIMCHIUSDT', 'RNTUSDT', 'DFDUSDT', 'RELUSDT', 'ELACUSDT', 'PTIUSDT', 'ZLOTUSDT', 'KTONUSDT', 'KSM1D3SUSDT', 'ETCUSDT', 'RGTUSDT', 'DEPUSDT', 'FEGUSDT', 'PERPUSDT', 'BATUSDT', 'DOGOUSDT', 'IONCUSDT', 'UFTUSDT', 'BDPUSDT', 'EOS1D3LUSDT', 'ANKRONSUSDT', 'EXPOUSDT', 'NEXOUSDT', 'BALUSDT', 'LRGUSDT', 'KNC1D3LUSDT', 'WORLDUSDT', 'MUSDUSDT', 'MOONLIGHTUSDT', 'PKFUSDT', 'SSNUSDT', 'HFIUSDT', 'TOMOUSDT', 'MNXUSDT', 'OCEANUSDT', 'SCUSDT', 'NRGUSDT', 'USDAUSDT', 'UMA1D3LUSDT', 'PAYTUSDT', 'KINDUSDT', 'FIC24MUSDT', 'TRUUSDT', 'SHIB1D3LUSDT', 'MISUSDT', 'KVAUSDT', 'DFYUSDT', 'KSM1D3LUSDT', 'JFIUSDT', 'ABBCUSDT', 'XEDUSDT', 'MATIC1D3LUSDT', 'YECUSDT', 'MOONUSDT', 'LPTUSDT', 'PYRKUSDT', 'SBREEUSDT', 'SNX1D3SUSDT', 'HUNGRYUSDT', 'IOGUSDT', 'SCHAUSDT', 'YNIUSDT', 'VSNUSDT', 'BACUSDT', 'SUSHIUSDT', 'TNBUSDT', 'WESTUSDT', '1INCH1D3SUSDT', 'HOPRUSDT', 'ROCKETUSDT', 'LTC1D3LUSDT', 'CoFiUSDT', 'LUNA1D3LUSDT', 'PTAUSDT', 'MOBUSDT', 'BHDUSDT', 'YFV1D3LUSDT', 'CREDITPROUSDT', 'YFIEUSDT', 'HOGUSDT', 'DERIUSDT', 'GALAUSDT', 'CVTUSDT', 'CHSUSDT', 'SHFTUSDT', 'AUVUSDT', 'GEEQUSDT', 'ENTSUSDT', 'DFT12MUSDT', 'SFPUSDT', 'BCSUSDT', 'MCOUSDT', 'STAKEUSDT', 'TRX1D3LUSDT', 'SNTUSDT', 'CVCUSDT', 'STMXUSDT', 'BNWUSDT', 'LFIUSDT', 'BITMUSDT', 'KISHUUSDT', 'XEQUSDT', 'BIDUSDT', 'LTXUSDT', 'WHXUSDT', 'B21USDT', 'VIKINGUSDT', 'ROCKSUSDT', 'MLNUSDT', 'LETUSDT', 'COOKUSDT', 'YFDUSDT', 'SWMUSDT', 'ARPAUSDT', 'SGTUSDT', 'ICPUSDT', 'TPTUSDT', 'AMPUSDT', 'CREAMUSDT', 'USDTnUSDT', 'STNUSDT', 'GUMUSDT', 'HANDYUSDT', 'PLFUSDT', 'FISUSDT', 'KDAUSDT', 'WOOUSDT', 'PRTUSDT', 'RAMPUSDT', 'ELONUSDT', 'PZMUSDT', 'XTZ1D3SUSDT', 'MDXUSDT', 'EOS1D3SUSDT', 'XFIUSDT', 'DUNUSDT', 'XSATUSDT', '0xCASHUSDT', 'SOULUSDT', 'KP3RUSDT', 'DOVUSDT', 'ALGOUSDT', 'CHNDUSDT', 'KEYUSDT', 'NEWUSDT', 'LIBFXUSDT', 'DBXCUSDT', 'VOXUSDT', 'DREPUSDT', 'DNTUSDT', 'IDEXUSDT', 'FIRETOKENUSDT', 'POCUSDT', 'YEFIMUSDT', 'HOTTOUSDT', 'SOGEUSDT', 'FLUXUSDT', 'UBTUSDT', 'COMBOUSDT', 'EPSUSDT', 'CRV1D3LUSDT', 'BTMUSDT', 'MIXUSDT', 'DAOFIUSDT', 'VBSWAPUSDT', 'PREMIAUSDT', 'XIVUSDT', 'KEEPUSDT', 'GOGOUSDT', 'BAL1D3LUSDT', 'PRCYUSDT', 'EGGUSDT', 'YEEUSDT', 'AQTUSDT', 'SAITOUSDT', 'LINK1D3LUSDT', 'TSLAUSDT', 'YOOSHIUSDT', 'CRV1D3SUSDT', 'MDUUSDT', 'YFHIUSDT', 'ERGUSDT', 'BPTUSDT', 'TORUSDT', 'ICXUSDT', 'RAKUSDT', 'UMA1D3SUSDT', 'COMPUSDT', 'DCRUSDT', 'ULTUSDT', 'MKRUSDT', 'YAMV3USDT', 'CYMTUSDT', 'DFUSDT', 'SWAPUSDT', 'SHRUSDT', 'CNSUSDT', 'YFIMUSDT', 'ICP1D3SUSDT', 'BIXBUSDT', 'ADA1D3SUSDT', 'SRMUSDT', 'BANDUSDT', 'PEOSUSDT', 'RFUELUSDT', 'NAOSUSDT', 'MKCYUSDT', 'RAZORUSDT', 'WEXUSDT', 'RINGUSDT', 'TRTLUSDT', 'KAIUSDT', 'USDJUSDT', 'JINDUSDT', 'SDTUSDT', 'BIFIUSDT', 'IRISUSDT', 'GUSDTUSDT', 'BOLTTUSDT', 'IPMUSDT', 'BZZUSDT', 'BAND1D3SUSDT', 'OXOUSDT', 'BLASTUSDT', 'USDXUSDT', 'BSCBUSDT', 'MANAUSDT', 'AQUAGOATUSDT', 'MEMEUSDT', '1INCHUSDT', 'FIL1D3SUSDT', 'PNKUSDT', 'REAUUSDT', 'BSCGOLDUSDT', 'FIL6MUSDT', 'WNLUSDT', 'ROOKUSDT', 'REEFUSDT', 'COTUSDT', 'OMG1D3SUSDT', 'VLKUSDT', 'DFTBSCUSDT', 'ZECUSDT', 'BAOFIUSDT', 'UNCXUSDT', 'DAMUSDT', 'SLPUSDT', 'GOFUSDT', 'DFIUSDT', 'BCTUSDT', 'CHIKUSDT', 'LCUSDT', 'APNUSDT', 'YFPROUSDT', 'GOMUSDT', 'DOKIUSDT', 'YFIIIUSDT', 'DACUSDT', 'GMEUSDT', 'SEROUSDT', 'FUTURAMAUSDT', 'DASHUSDT', 'FIDAUSDT', 'CYTRUSDT', 'ANIUSDT', 'DOGDEFIUSDT', 'UTUUSDT', 'HOTUSDT', 'GEROUSDT', 'HELMETUSDT', 'JRTUSDT', 'LEASHUSDT', 'KLPUSDT', 'IMGUSDT', 'SEELEUSDT', 'LFCUSDT', 'EMUSDT', 'FRENUSDT', 'ETHUSDT', 'FILDAUSDT', 'GNOUSDT', 'MTTCOINUSDT', 'ALPHAUSDT', 'PAMPUSDT', 'DIXTUSDT', 'BAFEUSDT', 'SOVIUSDT', 'YFOSUSDT', 'NOIAUSDT', 'B20USDT', 'NESTUSDT', 'BRYUSDT', 'HAPIUSDT', 'LTC1D3SUSDT', 'QUICKUSDT', 'GARDUSDT', 'MEDIBITUSDT', 'ARESUSDT', 'DUCKDAOUSDT', 'CATEUSDT', 'STCUSDT', 'GGTUSDT', 'SUMOUSDT', 'XTKUSDT', 'GFXUSDT', 'MTETH2308USDT', 'QTUMUSDT', 'DOCKUSDT', 'LAMBUSDT', 'KP3RBUSDT', 'BONEUSDT', 'BUYUSDT', 'FIL1D3LUSDT', 'LTOUSDT', 'YFNUSDT', 'OPMUSDT', 'KIWIUSDT', 'YFI1D3SUSDT', 'MRCHUSDT', 'SATOZUSDT', 'GOATUSDT', 'VJCUSDT', 'BNT1D3SUSDT', 'PERLUSDT', 'BRGUSDT', 'HALVUSDT', 'APCUSDT', 'COSUSDT', 'HPAYUSDT', 'MOFIUSDT', 'CNNSUSDT', 'PAXUSDT', 'OBSUSDT', 'NNDUSDT', 'OMG1D3LUSDT', 'XDCUSDT', 'DRYCAKEUSDT', 'ATPUSDT', 'KLTUSDT', 'BBGCUSDT', 'GUSDUSDT', 'MTFILUSDT', 'BASUSDT', 'CUFIUSDT', 'MANDIUSDT', 'YFIIUSDT', 'FTMUSDT', 'INXUSDT', 'PNETWORKUSDT', 'YFV1D3SUSDT', 'CAKEUSDT', 'DOTUSDT', 'STRIUSDT', 'CBTUSDT', 'XRP1D3LUSDT', 'SFIUSDT', 'YFI1D3LUSDT', 'PHOONUSDT', 'XEPUSDT', 'KLVUSDT', 'ECOINUSDT', 'VISRUSDT', 'UNIUSDT', 'ATOMUSDT', 'TRXUSDT', 'CWSUSDT', 'FEGBSCUSDT', 'XRPUSDT', 'LABRAUSDT', 'DOVEUSDT', 'ACEDUSDT', 'YOTUSDT', 'YFFSUSDT', 'ASTUSDT', 'MFFUSDT', 'TERAUSDT', 'AAPLUSDT', 'BAGSUSDT', 'DMSTUSDT', 'REPUSDT', 'YRISEUSDT', 'IPXUSDT', 'AEUSDT', 'UNI1D3SUSDT', 'EFTUSDT', 'BORUSDT', 'PMONUSDT', 'MOONTOKENUSDT', 'TAPUSDT', 'NAUTUSDT', 'SWFLUSDT', 'DXDUSDT', 'DMCHUSDT', 'VETUSDT', 'SXPUSDT', 'KOBEUSDT', 'AZUSDT', 'XDEXUSDT', 'HMRUSDT', 'ZILUSDT', 'DSDUSDT', 'EMRALSUSDT', 'ONGUSDT', 'ONTUSDT', 'PNIXUSDT', 'HOKKUSDT', 'CFXUSDT', 'MASK1D3SUSDT', 'FEIUSDT', 'RLCUSDT', 'ONCUSDT', 'HTBUSDT', 'RADUSDT', 'INSURUSDT', 'SWAGUSDT', 'GHOSTUSDT', 'CSOULUSDT', 'SWRVUSDT', 'PHAUSDT', 'DONKUSDT', 'ODDZUSDT', 'TOKENUSDT', 'SPDRUSDT', 'DUCKUSDT', 'NCATUSDT', 'OMGUSDT', 'CICCUSDT', 'YFFCUSDT', 'GNCUSDT', 'RAYUSDT', 'YFBTUSDT', 'DEROUSDT', 'BINGUSUSDT', 'CHZUSDT', 'LCGUSDT', 'AYAUSDT', 'DEXTUSDT', 'GXIUSDT', 'PUMLUSDT', 'XD100USDT', 'DUCKFINANCEUSDT', 'INTXUSDT', 'DZIUSDT', 'WOO6MUSDT', 'VKTUSDT', 'DYPUSDT', 'OPENUSDT', 'CUBICUSDT', 'BLESUSDT', 'MASKUSDT', 'RUNEUSDT', 'PASSUSDT', 'PAWSUSDT', 'GONUSDT', 'DEGOUSDT', 'LDOUSDT', 'SACUSDT', 'CRVUSDT', 'ZPAEUSDT', 'BOXUSDT', 'MATIC1D3SUSDT', 'KNC1D3SUSDT', 'XLM1D3SUSDT', 'LGCYUSDT', 'ARUSDT', 'TAIUSDT', 'STORJUSDT', 'XLM1D3LUSDT', 'ESDUSDT', 'REFIUSDT', 'FROZENUSDT', 'YFIIGUSDT', 'GOLDRUSDT', 'HAVYUSDT', 'UFOUSDT', 'NYANUSDT', 'YOLKUSDT', 'CPUUSDT', 'YTNBUSDT', 'CEXLTUSDT', 'YLFIUSDT', 'TORNUSDT', 'TVKUSDT', 'GOCUSDT', 'ONXUSDT', 'CRBNUSDT', 'TOPUSDT', 'ASSUSDT', 'PARAUSDT', 'BOLTUSDT', 'OXTUSDT', 'AUDIOUSDT', 'BLTUSDT', 'MINAUSDT', 'MWCUSDT', 'SKLUSDT', 'MAHAUSDT', 'DKAUSDT', 'COVERUSDT', 'UNCUSDT', 'ULUUSDT', 'JULDUSDT', 'POLSUSDT', 'EOSUSDT', 'POFIUSDT', 'BARTUSDT', 'MISTUSDT', 'SPHTXUSDT', 'HXROUSDT', 'NICHEMANUSDT', 'XORUSDT', 'YFICUSDT', 'BORAUSDT', 'LEADUSDT', 'DOGE1D3SUSDT', 'FLMUSDT', 'DEPTHUSDT', 'USFUSDT', 'YFFIUSDT', 'ZABAKUUSDT', 'MARTKUSDT', 'FSCCUSDT', 'LBCUSDT', 'PEGUSDT', 'PTDUSDT', 'BTCUSDT', 'MTDRUSDT', 'SHIBUSDT', 'L2PUSDT', 'FRAXUSDT', 'PDEXUSDT', 'ECLIPSEUSDT', 'TIDALUSDT', 'BQTUSDT', 'XCURUSDT', 'XCASHUSDT', 'BNSUSDT', 'UNI1D3LUSDT', 'DODOUSDT', 'YUSRAUSDT', 'MTTUSDT', 'ALTUSDT', 'FIROUSDT', 'RETRYUSDT', 'HUSDUSDT', 'UBXUSDT', 'YFFIIUSDT', 'CRTUSDT', 'DOWSUSDT', 'BAKEUSDT', 'DACCUSDT', 'SFMUSDT', 'BUDUSDT', 'JTUSDT', 'DSUSDT', 'BAASUSDT', 'MOMOUSDT', 'SUSHI1D3SUSDT', 'AVSUSDT', 'BFCUSDT', 'ELENAUSDT', 'WNXMUSDT', 'ARAWUSDT', 'ANCUSDT', 'YFIAGUSDT', 'ZEONUSDT', 'YIELDUSDT', 'HNTUSDT', 'ANJUSDT', 'FORUSDT', 'YFIVEUSDT', 'BTT1D3LUSDT', 'LASUSDT', 'HNSUSDT', 'YFILDUSDT', 'YCTUSDT', 'LNKOUSDT', 'TWTUSDT', 'WDXUSDT', 'COBITUSDT', 'ZKSUSDT', 'CRUUSDT', 'AIOUSDT', 'DOGEUSDT', 'NCTUSDT', 'BXHUSDT', 'USDNUSDT', 'ALCXUSDT', 'UBUUSDT', 'FIL12MUSDT', 'YFB2USDT', 'USDCUSDT', 'MMONUSDT', 'PICKLEUSDT', 'GRAMUSDT', 'HYFIIUSDT', 'TLMUSDT', 'INFTUSDT', 'BONFIREUSDT', 'LMCHUSDT', 'EXRDUSDT', 'WISEUSDT', 'PFIDUSDT', 'SANSHUUSDT', 'AZUKIUSDT', 'YFEUSDT', 'THETAUSDT', 'XLABUSDT', 'YCAKUSDT', 'IQEVPDUSDT', 'WAVESUSDT', 'TUSDUSDT', 'EARNUSDT', 'BTCVUSDT', 'LPOOLUSDT', 'RVNUSDT', 'WICCUSDT', 'MATTERUSDT', 'BONDLYUSDT', 'EURSUSDT', 'NUUSDT', 'XTMUSDT', 'EPICUSDT', 'pDAIUSDT', 'ETIUSDT', 'PIEUSDT', 'FINUSDT', 'ACTPUSDT', 'CWAPUSDT', 'BTCSTUSDT', 'DOUGHUSDT', 'QDAOUSDT', 'YFLUSDT', 'SENTUSDT', 'KAVAUSDT', 'PPAYUSDT', 'HLLUSDT', 'LSCUSDT', 'MSSUSDT', 'FARMUSDT', 'HMXUSDT', 'FMGUSDT', 'XIOUSDT', 'IFEXUSDT', 'RAIUSDT', 'TKOUSDT', 'GENEUSDT', 'VIKKYUSDT', 'API3USDT', 'GNYUSDT', 'APIXUSDT', 'SNX1D3LUSDT', 'SOCUSDT', 'POCRUSDT', 'CPTLUSDT', 'PHOUSDT', 'DOGGYUSDT', 'DCPUSDT', 'TFUELUSDT', 'DFTUSDT', 'AAVEUSDT', 'UTKUSDT', 'ALPACAUSDT', 'FREEUSDT', 'JMTUSDT', 'BDOUSDT', 'LTCUSDT', 'ADELUSDT', 'MEETONEUSDT', 'UNIFUSDT', 'LINK1D3SUSDT', 'HIVEUSDT', 'BAND1D3LUSDT', 'FIOUSDT', 'PONDUSDT', 'ARMORUSDT', 'TEPUSDT', 'YEAUSDT', 'WOWUSDT', 'SHEEPUSDT', 'YFOUSDT', 'FBNUSDT', 'RRBUSDT', 'RICHUSDT', 'GTCUSDT', 'DCNTUSDT', 'ROSEUSDT', 'GEARUSDT', 'QQQUSDT', 'BNXUSDT', 'LQTYUSDT', 'BLITZUSDT', 'BNTUSDT', 'NIOPUSDT', 'TKINUUSDT', 'XLMUSDT', 'DICEUSDT', 'BZRXUSDT', 'TANGOUSDT', 'YFII1D3SUSDT', 'STONKUSDT', 'YASUSDT', 'CLIMBUSDT', 'VGOUSDT', 'SNXUSDT', 'BOOSTUSDT', 'PIGUSDT', 'SHDUSDT', 'SALUSDT', 'CNBUSDT', 'PLTUSDT', 'GHDUSDT', 'SFNUSDT', 'RPLUSDT', 'MTLUSDT', 'ENJUSDT', 'AWTUSDT', 'YFII1D3LUSDT', 'FCTUSDT', 'PUNDIXUSDT', 'STEELUSDT', 'KUNUSDT', 'POOLUSDT', 'WAVES1D3LUSDT', 'MASSUSDT', 'ROOBEEUSDT', 'YFISUSDT', 'WNXM1D3SUSDT', 'ELTBUSDT', 'BCHUSDT', 'FMLUSDT', 'BALPHAUSDT', 'LITENTRYUSDT', 'TFFUSDT', 'SOLUSDT', 'EMAXUSDT', 'MBN1USDT', 'FORCEUSDT', 'GDMUSDT', 'MIR1D3LUSDT', 'TFBUSDT', 'BTTUSDT', 'AERGOUSDT', 'SOLOUSDT', 'VALUEUSDT', 'SMARTUSDT', 'DFYNUSDT', 'ZUCUSDT', 'PLRUSDT', 'PANTHERUSDT', 'SANDUSDT', 'NTXUSDT', 'FNXUSDT', 'ANRXUSDT', 'SPEUSDT', 'MCTPUSDT', 'FSNUSDT', 'BTXUSDT', 'MBONKUSDT', 'UMAUSDT', 'MOONSHOTUSDT', 'XPCUSDT', 'SAFEMOONUSDT', 'ANYUSDT', 'LVGCUSDT', 'GXCUSDT', 'BSDUSDT', 'WPTUSDT', 'OGXUSDT', 'UNNUSDT', 'WSGUSDT', 'IOSTUSDT', 'SFRUSDT', 'MUSEUSDT', 'AXEUSDT', 'SEURUSDT', 'GRTUSDT', 'PROSUSDT', 'ENVUSDT', 'CTASKUSDT', 'COUUSDT', 'DESHUSDT', 'DELTAUSDT', 'BTC1D3LUSDT', 'EDGUSDT', 'WING1USDT', 'YFOXUSDT', 'HYDUSDT', 'DHTUSDT', 'RNDRUSDT', 'STPTUSDT', 'SHOPXUSDT', 'BUIDLUSDT', 'BELUSDT', 'nUSDTUSDT', 'MBNUSDT', 'SIUSDT', 'RIFUSDT', 'KINEUSDT', 'FEXUSDT', 'XEMUSDT', 'THETA1D3LUSDT', 'GYSRUSDT', 'SAFEICARUSUSDT', 'LARUSDT', 'USDQUSDT', 'PAPELUSDT', 'FOXUSDT', 'PLOTUSDT', 'YFIDUSDT', 'ALICEUSDT', 'FISHUSDT', 'LIENUSDT', 'NEAR1YUSDT', 'EIDOSUSDT', 'RACAUSDT', 'AACUSDT', 'SBDOUSDT', 'DFGLUSDT', 'COREUSDT', 'DMGUSDT', 'GAMEUSDT', 'MTFUSDT', 'DFNUSDT', 'BLACKUSDT', 'ETH1D3LUSDT', 'BLOCUSDT', 'ALBTUSDT', 'ZOROUSDT', 'WATCHUSDT', 'ENERGYUSDT', 'XRP1D3SUSDT', 'CNTMUSDT', 'TFBXUSDT', 'HEGICUSDT', 'USDPUSDT', 'LONUSDT', 'SAFEPUSDT', 'APYUSDT', 'BETUSDT', 'SAKEUSDT', 'NBXUSDT', 'COMP1D3SUSDT', 'BNBUSDT', 'BIPUSDT', 'MNTK2201USDT', 'ONSUSDT', 'FINCUSDT', 'QTUSDT', 'LINKUSDT', 'EVOLUTIONUSDT', 'SURFUSDT', 'DGXUSDT', 'BELTUSDT', 'OSCUSDT', 'NMRUSDT', 'ALOHAUSDT', 'FIREUSDT', 'SWLUSDT', 'TCOUSDT', 'DEVUSDT', 'YFDTUSDT', 'CKBUSDT', 'BHCUSDT', 'IDLEUSDT', 'IOTXUSDT', 'AKITAUSDT', 'SFGUSDT', 'AXAUSDT', 'STAUSDT', 'ACHUSDT', 'UMEUSDT', 'PIKACHUUSDT', 'PMEERUSDT', 'ADAUSDT', 'MASK1D3LUSDT', 'MIR1D3SUSDT', 'BEAMUSDT', 'SPPUSDT', 'ANKRUSDT', 'HTUSDT', 'MMDAUSDT', 'PGNUSDT', 'BTCBUSDT', 'JSTUSDT', 'FUNUSDT', 'BCCUSDT', 'FWATCHUSDT', 'THETA1D3SUSDT', 'ETH1D3SUSDT', 'YFIVUSDT', 'KARMAUSDT', 'ORNUSDT', 'NIMUSDT', 'ADA1D3LUSDT', 'DFLUSDT', 'PEARLUSDT', 'PROTUSDT', 'FDSUSDT', 'DAOUSDT', 'WHALEUSDT', 'BONDUSDT', 'AXIAV3USDT', 'ATRIUSDT', 'TITANUSDT', 'XGMUSDT', 'VOLLARUSDT', 'MIRUSDT', 'SUSDUSDT', 'BSTUSDT', 'KGOUSDT', 'OGNUSDT', 'MANGOUSDT', 'LUAUSDT', 'CELUSDT', 'KANGALUSDT', 'RAZEUSDT', 'GRSUSDT', 'NRVUSDT', 'BUILDUSDT', 'WNXM1D3LUSDT', 'BLZUSDT', 'ROOMUSDT', 'CAPSUSDT', 'HTDFUSDT', 'CVPUSDT', 'OROUSDT', 'DATAUSDT', 'YETIUSDT', 'BAL1D3SUSDT', 'EOSCUSDT', 'DOT1D3LUSDT', 'KSMUSDT', 'GLQUSDT', 'ZEBUSDT', 'IRONUSDT', 'SMTYUSDT', 'FARUSDT', 'INVEUSDT', 'HAKKAUSDT', 'YFIUSDT', 'ACSIUSDT', 'CYCUSDT', 'WENMOONUSDT', 'GMCIUSDT', 'CHRUSDT', 'BIRUSDT', 'FYZUSDT', 'BTCPUSDT', 'SKNUSDT', 'PLZUSDT', 'COOKIEUSDT', 'BASKUSDT', 'PIZZAUSDT', 'ESHUSDT', 'APEUSDT', 'LAVAUSDT', 'KONOUSDT', 'AUTOUSDT', 'INFSUSDT', 'NYZOUSDT', 'DISTXUSDT', 'SENSOUSDT', 'ETHAUSDT', 'OGOUSDT', 'MOONMOONUSDT', 'ARROUSDT', 'SHOUSDT', 'IABUSDT', 'VIDTUSDT', 'DUSKUSDT', 'LASHUSDT', 'PSWAPUSDT', 'PCXUSDT', 'DDRUSDT', 'DORAUSDT', 'KYLUSDT', 'TUBERUSDT', 'CORNUSDT', 'XRTUSDT', 'GENUSDT', 'COSHIUSDT', 'CWVUSDT', 'NSUREUSDT', 'RAMENUSDT', 'YLABUSDT', 'SBEARUSDT', 'KATANAUSDT', 'UNFIUSDT', 'DOPUSDT', 'PHXUSDT', 'ELAMAUSDT', 'ERNUSDT', 'SAFEBTCUSDT', 'HAUSUSDT', 'KABOSUUSDT', 'MICUSDT']
